project:
  type: book
  output-dir: _book

book:
  title: "Machine Learning with R and Python"
  author: "Don Hale"
  date: "09/22/2025"
  chapters:
    - index.qmd
    - introduction.qmd
    - resampling-model-selection.qmd
    - resampling-model-selection-python.qmd
    - generalized-additive-models-r.qmd
    - generalized-additive-models-python.qmd
    - Tree_Based_R.qmd
    - Tree_Based_Python2.qmd
    - rf-xgb-params.qmd
    - neural-network-models.qmd
    - naive-bayes-models.qmd
    - model-agnostic-interpretability.qmd
    - support-vector-machines.qmd

# Use Jupyter for Python execution
jupyter: python3

execute:
  kernel: python3
  daemon: false
  freeze: auto
  keep-md: false
  cache: true
  echo: true
  warning: false
  message: false
  python:
    path: "/opt/anaconda3/bin/python"

# Tell Quarto explicitly where Python is located
engine: "/opt/anaconda3/bin/python"

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
  pdf:
    documentclass: scrreprt


